[project]
name = "jijhandson"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "jijzept-sdk[all]>=2025.3.30",
    "jupyter>=1.1.1",
    "jupyter-book>=1.0.4.post1",
    "seaborn>=0.13.2",
]
